version: '3'

services:

  proxy:
    image: nginx:latest
    container_name: proxy
    depends_on:
      - server 
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 801:80

  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    restart: on-failure

  server:
    container_name: server
    build: ./server
    ports:
      - 5000:5000
    restart: on-failure

